<?php

namespace ContainerVh8o0nf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OperationController' shared autowired service.
     *
     * @return \App\Controller\OperationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/OperationController.php';

        return $container->services['App\\Controller\\OperationController'] = new \App\Controller\OperationController();
    }
}
