<?php

namespace ContainerVh8o0nf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperationsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OperationsService' shared autowired service.
     *
     * @return \App\Service\OperationsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/OperationsService.php';

        return $container->privates['App\\Service\\OperationsService'] = new \App\Service\OperationsService(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Interfaces\\AddOperation'] ?? ($container->privates['App\\Interfaces\\AddOperation'] = new \App\Interfaces\AddOperation()));
            yield 1 => ($container->privates['App\\Interfaces\\DiffOperation'] ?? ($container->privates['App\\Interfaces\\DiffOperation'] = new \App\Interfaces\DiffOperation()));
            yield 2 => ($container->privates['App\\Interfaces\\DivOperation'] ?? ($container->privates['App\\Interfaces\\DivOperation'] = new \App\Interfaces\DivOperation()));
            yield 3 => ($container->privates['App\\Interfaces\\MulOperation'] ?? ($container->privates['App\\Interfaces\\MulOperation'] = new \App\Interfaces\MulOperation()));
        }, 4));
    }
}
