<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVh8o0nf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVh8o0nf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVh8o0nf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVh8o0nf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVh8o0nf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vh8o0nf',
    'container.build_id' => 'a68522c0',
    'container.build_time' => 1641784496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVh8o0nf');
